sonar.organization=dierodfer
sonar.projectKey=dierodfer_demo-jam
sonar.projectName=demo-jam

sonar.sources=backend-java/src/main,frontend-react/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**
sonar.java.binaries=backend-java/target/classes
sonar.sourceEncoding=UTF-8
